const state = { view: 'chat', config: null, token: '', pairing: null, tasks: [], history: [], capabilities: [], activity: {}, messages: JSON.parse(localStorage.getItem('chdevagent.messages') || '[]') };
const $ = (selector) => document.querySelector(selector);
const api = (path, options = {}) => fetch(`http://127.0.0.1:8228${path}`, { ...options, headers: { 'content-type': 'application/json', ...(state.token ? { authorization: `Bearer ${state.token}` } : {}), ...(options.headers || {}) } }).then(async response => { const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`); return data; });

function escapeHtml(value = '') { return String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char])); }
function showView(view) { state.view = view; document.querySelectorAll('.view').forEach(node => node.classList.toggle('active', node.id === `view-${view}`)); document.querySelectorAll('.nav-item[data-view]').forEach(node => node.classList.toggle('active', node.dataset.view === view)); const labels = { chat: ['TRỢ LÝ / TRÒ CHUYỆN', 'Trò chuyện với ChDevAgent'], agent: ['AGENT / THỰC THI', 'Agent thực thi'], files: ['WORKSPACE / TỆP', 'Tệp cục bộ'], tasks: ['HISTORY / AUDIT', 'Lịch sử nhiệm vụ'], permissions: ['CONTROL / CAPABILITIES', 'Quyền truy cập'], settings: ['SYSTEM / SETTINGS', 'Cài đặt'] }; $('#view-eyebrow').textContent = labels[view][0]; $('#view-title').textContent = labels[view][1]; if (view === 'files') loadFiles(); if (view === 'tasks') renderHistory(); if (view === 'permissions') renderCapabilities(); }
function pushMessage(role, text) { state.messages.push({ role, text, time: new Date().toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' }) }); localStorage.setItem('chdevagent.messages', JSON.stringify(state.messages)); renderMessages(); }
function renderMessages() { const root = $('#chat-messages'); if (!state.messages.length) { root.innerHTML = '<div class="empty-chat"><span>✦</span><h4>Bắt đầu từ một câu hỏi</h4><p>Ví dụ: “Workspace của tôi đang lưu ở đâu?” hoặc “Giải thích quyền đọc tệp.”</p></div>'; return; } root.innerHTML = state.messages.map(message => `<div class="message ${message.role}"><small>${message.role === 'user' ? 'BẠN' : 'TRỢ LÝ'} · ${escapeHtml(message.time)}</small>${escapeHtml(message.text)}</div>`).join(''); root.scrollTop = root.scrollHeight; }
function renderTasks() { const root = $('#agent-tasks'); if (!state.tasks.length) { root.innerHTML = '<div class="panel loading">Chưa có nhiệm vụ. Hãy tạo một preview ở bên trên.</div>'; return; } root.innerHTML = state.tasks.map(task => `<article class="task-card"><header><b>${escapeHtml(task.instruction)}</b><span class="status-pill">${escapeHtml((task.status || '').replaceAll('_', ' ').toUpperCase())}</span></header><div class="preview">${escapeHtml(task.preview?.action || 'Đọc dữ liệu trong workspace')}<br><small>Phạm vi: ${escapeHtml(task.preview?.scope || '/workspace')} · Quyền: ${escapeHtml(task.preview?.permission || 'chỉ đọc')}</small></div>${task.result?.content ? `<p>${escapeHtml(task.result.content)}</p>` : ''}${task.status === 'awaiting_approval' ? `<div class="task-actions"><button class="approve" data-action="approve" data-id="${task.id}">Phê duyệt</button><button data-action="reject" data-id="${task.id}">Từ chối</button></div>` : ''}</article>`).join(''); }
function renderHistory() { const root = $('#history-list'); root.innerHTML = state.history.length ? state.history.map(item => `<article class="history-card"><header><b>${escapeHtml(item.type || 'Sự kiện')}</b><span>${escapeHtml(item.at || '')}</span></header><p>${escapeHtml(item.message || item.action || JSON.stringify(item))}</p></article>`).join('') : '<div class="panel loading">Chưa có lịch sử. Các task và quyền sẽ xuất hiện ở đây.</div>'; }
function renderCapabilities() { const root = $('#permission-list'); root.innerHTML = state.capabilities.length ? state.capabilities.map(item => `<article class="permission-card"><header><b>${escapeHtml(item.label || item.name)}</b><span class="status-pill">${item.enabled ? 'ĐANG BẬT' : 'ĐANG TẮT'}</span></header><p>${escapeHtml(item.description || 'Capability cần quyền riêng và preview trước khi dùng.')}</p></article>`).join('') : '<div class="panel loading">Đang tải danh sách capability…</div>'; }
function renderActivity() { const activity = state.activity || {}; const progress = Math.max(0, Math.min(100, Number(activity.progress || 0))); $('#live-progress').style.width = `${progress}%`; $('#live-percent').textContent = `${progress}%`; $('#live-step').textContent = activity.currentStep || 'Chờ yêu cầu'; $('#live-summary').textContent = activity.summary || 'PC Agent sẵn sàng.'; }
async function refresh() { try { const [status, tasks, history, capabilities] = await Promise.all([api('/api/status'), api('/api/tasks'), api('/api/history'), api('/api/capabilities')]); state.activity = status.activity || {}; state.tasks = tasks.tasks || []; state.history = history.events || history.audit || []; state.capabilities = capabilities.capabilities || []; $('#connection-label').textContent = 'Đã kết nối'; $('#connection-detail').textContent = 'Agent nội bộ đang hoạt động'; $('.status-dot').style.background = 'var(--lime)'; renderActivity(); renderTasks(); if (state.view === 'tasks') renderHistory(); if (state.view === 'permissions') renderCapabilities(); } catch (error) { $('#connection-label').textContent = 'Chưa kết nối'; $('#connection-detail').textContent = error.message || 'Đang khởi động Agent'; $('.status-dot').style.background = 'var(--gold)'; } }
async function pairIfNeeded() { try { const data = await api('/api/pairing/status'); if (!data.paired && data.code) { state.pairing = data; } else if (data.token) state.token = data.token; } catch {} }
async function createTask() { const input = $('#task-input'); const instruction = input.value.trim(); if (!instruction) return; try { await api('/api/tasks', { method: 'POST', body: JSON.stringify({ instruction, requestedTools: ['file.list'], relativePath: '.' }) }); input.value = ''; pushMessage('user', `Tác vụ: ${instruction}`); await refresh(); } catch (error) { pushMessage('assistant', `Chưa tạo được task: ${error.message}`); } }
async function approveTask(id, action) { try { await api(`/api/tasks/${id}/${action}`, { method: 'POST', body: '{}' }); await refresh(); } catch (error) { pushMessage('assistant', `Không thể cập nhật task: ${error.message}`); } }
async function sendChat() { const input = $('#chat-input'); const text = input.value.trim(); if (!text) return; input.value = ''; pushMessage('user', text); const lower = text.toLowerCase(); let reply = 'Tôi đã ghi nhận. Nếu yêu cầu cần thao tác trên PC, hãy chuyển sang Agent thực thi để xem preview và phê duyệt.'; if (lower.includes('workspace') || lower.includes('lưu')) reply = `Dữ liệu hiện được lưu trong workspace: ${state.config?.workspace || 'thư mục đã chọn trong Cài đặt'}.`; if (lower.includes('quyền')) reply = 'ChDevAgent dùng quyền theo capability. Quyền đọc workspace đang bật; shell, ghi/xóa file, trình duyệt và điều khiển hệ thống vẫn tắt mặc định.'; setTimeout(() => pushMessage('assistant', reply), 180); }
async function loadFiles() { const root = $('#file-list'); try { const data = await api('/api/recent-files'); const files = data.files || []; root.innerHTML = files.length ? files.map(file => `<div class="file-row"><span>▤ ${escapeHtml(file.relativePath || file.name)}</span><small>${escapeHtml(file.size || '')}</small></div>`).join('') : '<div class="loading">Chưa có tệp gần đây.</div>'; } catch (error) { root.innerHTML = `<div class="loading">Không tải được danh sách tệp: ${escapeHtml(error.message)}</div>`; } }
async function chooseRoot() { const result = await window.chdevagentDesktop.chooseDataRoot(); if (!result) return; state.config = result; $('#onboarding-path').textContent = result.dataRoot; $('#workspace-path').textContent = result.workspace; $('#settings-root').textContent = result.dataRoot; $('#continue-onboarding').disabled = false; }
function openApp() { $('#onboarding').classList.add('hidden'); $('#app').classList.remove('hidden'); showView('chat'); renderMessages(); refresh(); setInterval(refresh, 2500); }
async function init() { state.config = await window.chdevagentDesktop.getConfig(); $('#onboarding-path').textContent = state.config.dataRoot; $('#workspace-path').textContent = state.config.workspace; $('#settings-root').textContent = state.config.dataRoot; $('#continue-onboarding').disabled = false; $('#onboarding').classList.remove('hidden'); await pairIfNeeded(); }

document.querySelectorAll('.nav-item[data-view]').forEach(node => node.addEventListener('click', () => showView(node.dataset.view)));
$('#continue-onboarding').addEventListener('click', openApp); $('#choose-root').addEventListener('click', chooseRoot); $('#change-root').addEventListener('click', chooseRoot); $('#open-data').addEventListener('click', () => window.chdevagentDesktop.openDataRoot()); $('#send-chat').addEventListener('click', sendChat); $('#chat-input').addEventListener('keydown', event => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); sendChat(); } }); $('#create-task').addEventListener('click', createTask); $('#refresh-status').addEventListener('click', refresh); $('#stop-task').addEventListener('click', async () => { await api('/api/stop', { method: 'POST', body: '{}' }); await refresh(); }); $('#emergency-stop').addEventListener('click', async () => { await api('/api/stop', { method: 'POST', body: '{}' }); await refresh(); }); $('#tool-menu').addEventListener('click', () => $('#tool-popover').classList.toggle('hidden')); document.querySelectorAll('#tool-popover button').forEach(button => button.addEventListener('click', () => { if (button.dataset.tool !== 'disabled') showView(button.dataset.tool); $('#tool-popover').classList.add('hidden'); })); $('#agent-tasks').addEventListener('click', event => { const button = event.target.closest('button[data-action]'); if (button) approveTask(button.dataset.id, button.dataset.action); }); window.chdevagentDesktop.onAgentLog(value => { $('#connection-detail').textContent = String(value).trim().slice(0, 90) || 'Agent nội bộ đang hoạt động'; });
init();
